[SERVICE]
    Parsers_File parsers.conf

[INPUT]
    Name        tail
    Path        /var/lib/docker/containers/*/*.log
    Parser      docker
    Tag         docker.*
    Mem_Buf_Limit 50MB
    Skip_Long_Lines On

[OUTPUT]
    Name        loki
    Match       docker.*
    Host  loki
    Port  3100
    Uri   /loki/api/v1/push
    tenant_id   tenant1
    labels      job=fluentbit,container_name=$container_name
