[SERVICE]
    Flush        5
    Daemon       Off
    Log_Level    info

[INPUT]
    Name         tail
    Path         /var/lib/docker/containers/*/*.log
    Parser       docker
    Tag          docker.*

[OUTPUT]
    Name         loki
    Match        docker.*
    Url          http://loki:3100/loki/api/v1/push
    TenantID     tenant1
    Labels       {job="docker-logs", container_name="${container_name}"}

