namespaces:
  action:
    type: resource
    relations:
      list_users: 
        tuple_to_userset:
          computed_userset:
            relation: member    
      create_user:
        tuple_to_userset:
          computed_userset:
            relation: member    
      update_user:
        tuple_to_userset:
          computed_userset:
            relation: member    
      delete_user:
        tuple_to_userset:
          computed_userset:
            relation: member    

  object:
    type: resource
    relations:
      read:
        union:
          - tuple_to_userset:
              computed_userset:
                relation: member     
          - tuple_to_userset:
              tupleset:
                relation: write
              computed_userset:
                relation: member
          # object_set
          - tuple_to_userset:
              tupleset:
                relation: belong
              computed_userset:
                relation: write
          - tuple_to_userset:
              tupleset:
                relation: belong
              computed_userset:
                relation: read
      write:
        union:
          - tuple_to_userset:
              computed_userset:
                relation: member
          - tuple_to_userset:
              tupleset:
                relation: belong
              computed_userset:
                relation: write

  object_set:
    type: resource
    relations:
      read:
        allow_subject_namespaces: [role]
        tuple_to_userset:
          computed_userset:
            relation: member     
      write: 
        allow_subject_namespaces: [role]
        tuple_to_userset:
          computed_userset:
            relation: member     
      belong:
        allow_subject_namespaces: [object]

  role:
    relations:
      member:
        allow_subject_namespaces: [user]
        computed_userset:
          relation: member
  user: {}