// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"authz/internal/engine/rbac"
	"authz/internal/handler/rest"
	"authz/internal/schema"
	"authz/internal/service"
	"authz/internal/util"
	"authz/internal/zanzibar"
	"context"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func NewRbacHandler(contextContext context.Context, lifecycleParallel *util.LifecycleParallel, db *gorm.DB) (*rbac.Handler, error) {
	schemaSchema, err := schema.NewSchema()
	if err != nil {
		return nil, err
	}
	reader := service.NewKafkaReader(lifecycleParallel)
	zanzibarMemoryImpl, err := zanzibar.NewZanzibarMemory(contextContext, lifecycleParallel, db, schemaSchema, reader)
	if err != nil {
		return nil, err
	}
	zanzibarLogicImpl := zanzibar.NewZanzibarLogic(db, zanzibarMemoryImpl, schemaSchema)
	rbacLogicImpl := rbac.NewRbacLogic(zanzibarLogicImpl, db, schemaSchema)
	handler := rbac.NewHandler(zanzibarLogicImpl, rbacLogicImpl)
	return handler, nil
}

func NewRestHandler(db *gorm.DB) *rest.Handler {
	kafkaDialer := service.NewKafkaDialer()
	handler := rest.NewHandler(db, kafkaDialer)
	return handler
}
