// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"authz/internal/engine/rbac"
	"authz/internal/pkg"
	"authz/internal/schema"
	"authz/internal/service"
	"authz/internal/service/database"
	"authz/internal/service/redis"
	"context"
)

// Injectors from wire.go:

func NewRbacHandler(contextContext context.Context, lifecycleParallel *pkg.LifecycleParallel) (*rbac.Handler, error) {
	db, err := database.New(lifecycleParallel)
	if err != nil {
		return nil, err
	}
	client := redis.New(lifecycleParallel)
	schemaSchema, err := schema.NewSchema()
	if err != nil {
		return nil, err
	}
	reader := service.NewKafkaReader(lifecycleParallel)
	zanzibarMemoryImpl, err := rbac.NewZanzibarMemory(contextContext, lifecycleParallel, db, schemaSchema, reader)
	if err != nil {
		return nil, err
	}
	zanzibarLogicImpl := rbac.NewZanzibarLogic(db, client, zanzibarMemoryImpl, schemaSchema)
	rbacLogicImpl := rbac.NewRbacLogic(zanzibarLogicImpl, db, schemaSchema)
	handler := rbac.NewHandler(zanzibarLogicImpl, rbacLogicImpl)
	return handler, nil
}
