// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"authz/internal/engine"
	"authz/internal/handler/connect"
	"authz/internal/logic"
	"authz/internal/pkg"
	"authz/internal/service/database"
	"authz/internal/service/redis"
	"context"
)

// Injectors from wire.go:

func NewConnectHandler(contextContext context.Context, lifecycle pkg.Lifecycle) (*connect.Handler, error) {
	db, err := database.New(lifecycle)
	if err != nil {
		return nil, err
	}
	client := redis.New(lifecycle)
	zanzibarEngineImpl, err := engine.NewZanzibarEngine(contextContext, db, client)
	if err != nil {
		return nil, err
	}
	zanzibarLogicImpl := logic.NewZanzibarLogic(db, client, zanzibarEngineImpl)
	rbacLogicImpl := logic.NewRbacLogic(zanzibarLogicImpl)
	handler := connect.NewHandler(zanzibarLogicImpl, rbacLogicImpl)
	return handler, nil
}
