apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgres
  namespace: authz
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: postgres
    database.port: 5432
    database.user: ${secrets:authz/debezium-secret:username}
    database.password: ${secrets:authz/debezium-secret:password}
    database.dbname: postgres
    database.server.name: pgserver1
    database.server.id: 184054
    publication.name: debezium
    slot.name: debezium_slot
    plugin.name: pgoutput
    topic.prefix: pg
    database.include.list: authz
    table.include.list: tuples
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: "false"
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: "false"
    schema.history.internal.kafka.bootstrap.servers: debezium-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.authz
    transforms: "unwrap"
    transforms.unwrap.type: "io.debezium.transforms.ExtractNewRecordState"
    transforms.unwrap.drop.tombstones: "true"
    transforms.unwrap.delete.handling.mode: "drop"
    transforms.unwrap.add.fields: "op"