mimir:
  structuredConfig:
    storage:
      backend: s3
      s3:
        endpoint: minio:9000
        bucket_name: mimir
        access_key_id: minio
        secret_access_key: minio123
        insecure: true
        s3forcepathstyle: true
