apiVersion: v1
kind: Secret
metadata:
  name: {{ include "debezium.fullname" . }}-debezium-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "debezium.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.debezium.username | b64enc }}
  password: {{ .Values.debezium.password | b64enc }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "debezium.fullname" . }}-connector-configuration-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "debezium.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["{{ include "debezium.fullname" . }}-debezium-secret"]
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "debezium.fullname" . }}-connector-configuration-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "debezium.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "debezium.fullname" . }}-debezium-connect-cluster-connect
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "debezium.fullname" . }}-connector-configuration-role
  apiGroup: rbac.authorization.k8s.io